# VuIO Server Configuration Example
# Copy this file to your platform's config directory and rename to config.toml
#
# Platform-specific config locations:
# - Native apps: ./config/config.toml
# - Docker: /config/config.toml (mounted volume)

[server]
port = 8080
interface = "0.0.0.0"
name = "VuIO"
uuid = "129c3ee9-4fd2-45ea-9f11-7a15e6d831ef"
ip = "192.168.1.126"

[network]
multicast_ttl = 4
announce_interval_seconds = 300
interface_selection = "Auto"  # Options: "Auto", "All", or specific interface name
# Note: SSDP port is hardcoded to 1900 (DLNA standard) and cannot be changed

[media]
scan_on_startup = true
watch_for_changes = true
cleanup_deleted_files = true
supported_extensions = [
    "mp4", "mkv", "avi", "mov", "wmv", "flv", "webm", "m4v", "mpg", "mpeg", "3gp", "ogv",
    "mp3", "flac", "wav", "aac", "ogg", "wma", "m4a", "opus", "ape",
    "jpg", "jpeg", "png", "gif", "bmp", "webp", "tiff", "svg"
]

# Add one or more media directories to monitor
[[media.directories]]
path = "/Users/alex/Movies"  # Change this to your actual media directory
recursive = true
# extensions = ["mp4", "mkv", "avi"]  # Optional: Override global extensions for this directory
# exclude_patterns = ["*.tmp", ".*"]  # Optional: Files/patterns to exclude

# Example: Additional media directory
# [[media.directories]]
# path = "/path/to/your/music"
# recursive = true
# extensions = ["mp3", "flac", "wav"]

[database]
path = "./config/media.db"  # Will use platform-appropriate default if not specified
vacuum_on_startup = false
backup_enabled = true

# ZeroCopy Database Configuration (optional - uses minimal defaults if not set)
# All values are optional and will use minimal defaults if not specified
[database.zerocopy]
# cache_mb = 2                          # Memory cache size in MB (1-1024, default: 1)
# index_size = 5000                     # Index cache entries (100-10M, default: 1000)
# batch_size = 500                      # Batch processing size (10-1M, default: 100)
# initial_file_size_mb = 2              # Initial DB file size in MB (1-1024, default: 1)
# max_file_size_gb = 2                  # Max DB file size in GB (1-100, default: 1)
# sync_frequency_secs = 120             # Sync frequency in seconds (1-3600, default: 60)
# enable_wal = true                     # Enable Write-Ahead Logging (default: true)
# enable_compression = false            # Enable compression (default: false)
# monitor_interval_secs = 900           # Performance monitoring interval (30-3600s, default: 600)