version: '3.8'

services:
  vuio-go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuio-go-local
    # network_mode: "host" is the easiest way to ensure SSDP (multicast) works reliably
    # without complex Docker network configurations.
    network_mode: "host"
    volumes:
      # Mount a local directory for your media files.
      # Place your movies, music, etc., in a 'media' folder next to this file.
      - ./media:/media
      # Mount a local directory for persistent configuration and the database.
      # The app will create config.toml and media.db here on first run.
      - ./config:/root/.config/vuio-go
    restart: unless-stopped