version: '3.8'

services:
  vuio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuio-server-local
    restart: unless-stopped
    network_mode: host
    
    # Add capabilities for better multicast support
    cap_add:
      - NET_ADMIN
      - NET_RAW
    
    # Ensure container has access to network interfaces
    privileged: false  # Start with false, can be changed to true if needed
    
    volumes:
      # Persist database
      - ./vuio-data:/data
      
      # Mount your media library (always read-only)
      # VuIO enforces read-only access to media files at the application level
      # Docker :ro mount provides additional security layer
      
      # Example 1: Single media directory
      - ./test-media:/media
      
      # Example 2: Multiple media directories
      # Mount each directory and configure via environment variable:
      # - /path/to/movies:/media/movies
      # - /path/to/tv-shows:/media/tv
      # - /path/to/music:/media/music
      # Then set: VUIO_MEDIA_DIRS=/media/movies,/media/tv,/media/music
      
      # Example 3: Network storage (NFS/SMB)
      # - type: bind
      #   source: /mnt/nas/media
      #   target: /media
      
    environment:
      # Server Configuration
      - VUIO_PORT=8080
      - VUIO_INTERFACE=0.0.0.0
      - VUIO_SERVER_NAME=VuIO DLNA Server
      - VUIO_UUID=550e8400-e29b-41d4-a716-446655440000  # Fixed UUID for consistency. CHANGE THIS if running multiple instances on same LAN
      - VUIO_IP=192.168.1.173  # Required for Docker host networking
      
      # Media Configuration
      - VUIO_MEDIA_DIRS=/media  # Comma-separated for multiple dirs: /media/movies,/media/tv,/media/music
      - VUIO_SCAN_ON_STARTUP=true
      - VUIO_WATCH_CHANGES=true
      - VUIO_CLEANUP_DELETED=true
      
      # Network Configuration
      - VUIO_MULTICAST_TTL=4
      - VUIO_ANNOUNCE_INTERVAL=300
      
      # Database Configuration
      - VUIO_DB_PATH=/data/vuio.db
      - VUIO_DB_VACUUM=false
      - VUIO_DB_BACKUP=true
      
      # ZeroCopy Database Configuration (optional - uses minimal defaults if not set)
      # - ZEROCOPY_CACHE_MB=2                    # Memory cache size (1-1024 MB, default: 1)
      # - ZEROCOPY_INDEX_SIZE=5000               # Index cache entries (100-10M, default: 1000)
      # - ZEROCOPY_BATCH_SIZE=500                # Batch processing size (10-1M, default: 100)
      # - ZEROCOPY_INITIAL_FILE_SIZE_MB=2        # Initial DB file size (1-1024 MB, default: 1)
      # - ZEROCOPY_MAX_FILE_SIZE_GB=2            # Max DB file size (1-100 GB, default: 1)
      # - ZEROCOPY_SYNC_FREQUENCY_SECS=120       # Sync frequency (1-3600 seconds, default: 60)
      # - ZEROCOPY_ENABLE_WAL=true               # Enable Write-Ahead Logging (default: true)
      # - ZEROCOPY_ENABLE_COMPRESSION=false      # Enable compression (default: false)
      # - ZEROCOPY_MONITOR_INTERVAL_SECS=900     # Performance monitoring interval (30-3600s, default: 600)
      
      # Enable debug logging
      - RUST_LOG=debug