version: '3.8'

services:
  vuio:
    image: ghcr.io/vuiodev/vuio:latest
    container_name: vuio-server
    restart: unless-stopped
    
    # Enable multicast for SSDP
    sysctls:
      - net.ipv4.ip_forward=1
    
    # Add NET_ADMIN capability for multicast
    cap_add:
      - NET_ADMIN
    
    ports:
      - "8080:8080/tcp"
      - "1900:1900/udp"
    
    volumes:
      - ./vuio-config:/config
      - /path/to/your/media:/media
      
    environment:
      - PUID=1000
      - PGID=1000
      - VUIO_PORT=8080
      - VUIO_MEDIA_DIR=/media
      - VUIO_SERVER_NAME=VuIO
      - VUIO_BIND_INTERFACE=0.0.0.0
      - VUIO_SSDP_INTERFACE=All  # Try broadcasting on all interfaces