#!/bin/sh
set -e

CONFIG_FILE="/config/config.toml"

# Create config directory if it doesn't exist
mkdir -p "$(dirname "$CONFIG_FILE")"

# Read existing UUID if present, so it's persisted across container restarts if /config is a volume.
UUID=""
if [ -f "$CONFIG_FILE" ]; then
    UUID=$(grep '^uuid' "$CONFIG_FILE" | sed 's/uuid = "\(.*\)"/\1/')
fi

# Generate a new UUID if none exists
if [ -z "$UUID" ]; then
    # Generate a new UUID using a fallback method that works in Alpine Linux
    if command -v uuidgen >/dev/null 2>&1; then
        UUID=$(uuidgen)
    else
        # Fallback: generate a simple UUID-like string using /proc/sys/kernel/random/uuid if available
        if [ -f /proc/sys/kernel/random/uuid ]; then
            UUID=$(cat /proc/sys/kernel/random/uuid)
        else
            # Last resort: generate a pseudo-UUID using date and random
            UUID=$(printf "%08x-%04x-%04x-%04x-%012x" \
                $(($(date +%s) % 4294967296)) \
                $((RANDOM % 65536)) \
                $((RANDOM % 65536)) \
                $((RANDOM % 65536)) \
                $((RANDOM % 281474976710656)))
        fi
    fi
    echo "Generated new UUID: $UUID"
else
    echo "Using existing UUID: $UUID"
fi

# Create the config file. This overwrites the file on every start to ensure it's up-to-date with env vars.
cat > "$CONFIG_FILE" <<EOF
# This file is auto-generated by docker-entrypoint.sh on container start.
# Do not edit this file directly. Use environment variables instead.

[server]
port = ${VUIO_PORT:-8080}
interface = "${VUIO_BIND_INTERFACE:-0.0.0.0}"
name = "${VUIO_SERVER_NAME:-VuIO}"
uuid = "$UUID"
EOF

# Continue with the rest of the config
cat >> "$CONFIG_FILE" <<EOF

[network]
ssdp_port = 1900
multicast_ttl = 4
announce_interval_seconds = 300
EOF

# Handle network interface selection for SSDP
SSDP_INTERFACE="${VUIO_SSDP_INTERFACE:-Auto}"
if [ "$SSDP_INTERFACE" = "Auto" ] || [ "$SSDP_INTERFACE" = "All" ]; then
    echo "interface_selection = { type = \"$SSDP_INTERFACE\" }" >> "$CONFIG_FILE"
else
    echo "interface_selection = { type = \"Specific\", value = \"$SSDP_INTERFACE\" }" >> "$CONFIG_FILE"
fi

cat >> "$CONFIG_FILE" <<EOF

[media]
scan_on_startup = true
watch_for_changes = true
cleanup_deleted_files = true
supported_extensions = [
    "mp4", "mkv", "avi", "mov", "wmv", "flv", "webm", "m4v", "mpg", "mpeg", "3gp", "ogv",
    "mp3", "flac", "wav", "aac", "ogg", "wma", "m4a", "opus", "ape",
    "jpg", "jpeg", "png", "gif", "bmp", "webp", "tiff", "svg"
]

[[media.directories]]
path = "${VUIO_MEDIA_DIR:-/media}"
recursive = true

[database]
path = "/config/media.db"
vacuum_on_startup = false
backup_enabled = true
EOF

echo "Configuration generated in $CONFIG_FILE"
cat "$CONFIG_FILE"

# Execute the command passed to the entrypoint (the CMD from the Dockerfile).
exec "$@"