version: '3.8'

services:
  vuio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuio-server-local
    restart: unless-stopped
    network_mode: host
    
    # Add capabilities for better multicast support
    cap_add:
      - NET_ADMIN
      - NET_RAW
    
    # Ensure container has access to network interfaces
    privileged: false  # Start with false, can be changed to true if needed
    
    volumes:
      # Persist configuration and database
      - ./vuio-config:/config
      # Mount your media library (adjust path as needed)
      - ./test-media:/media
      
    environment:
      # User/Group ID mapping
      - PUID=1000  # Run 'id -u' to find your user ID
      - PGID=1000  # Run 'id -g' to find your group ID
      
      # Application configuration
      - VUIO_PORT=8080
      - VUIO_MEDIA_DIR=/media
      - VUIO_SERVER_NAME=VuIO
      - VUIO_BIND_INTERFACE=0.0.0.0
      
      # Set server IP for DLNA announcements (Required for Docker host networking)
      # This ensures DLNA announcements use the correct IP address
      - VUIO_SERVER_IP=192.168.1.126  # Your host IP address
      
      # Set SSDP port to avoid conflicts (port 1900 is in use)
      - VUIO_SSDP_PORT=1902
      
      # Enable debug logging
      - RUST_LOG=debug