version: '3.8'

# macOS Docker Desktop specific configuration
# Note: DLNA discovery may have limitations due to Docker Desktop networking on macOS

services:
  vuio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vuio-server-macos
    restart: unless-stopped
    
    # Use bridge networking with explicit ports for macOS
    ports:
      - "8080:8080/tcp"
      - "1900:1900/udp"
      - "1902:1902/udp"
    
    volumes:
      # Persist configuration and database
      - ./vuio-config:/config
      # Mount your media library (adjust path as needed)
      - ./test-media:/media
      
    environment:
      # User/Group ID mapping
      - PUID=1000  # Run 'id -u' to find your user ID
      - PGID=1000  # Run 'id -g' to find your group ID
      
      # Application configuration
      - VUIO_PORT=8080
      - VUIO_MEDIA_DIR=/media
      - VUIO_SERVER_NAME=VuIO-macOS
      - VUIO_BIND_INTERFACE=0.0.0.0
      
      # Network configuration for macOS Docker Desktop
      - VUIO_SSDP_INTERFACE=eth0
      - VUIO_SSDP_PORT=1902
      
      # CRITICAL: Set this to your Mac's actual IP address for DLNA discovery
      # Find it with: ifconfig | grep "inet " | grep -v 127.0.0.1
      # Uncomment and set your actual IP:
      # - VUIO_SERVER_IP=192.168.1.126  # Replace with your actual Mac IP
      # Note: host.docker.internal may not work for DLNA clients
      
      # Enable debug logging to troubleshoot networking
      - RUST_LOG=debug
      
    # Use special hostname for Docker Desktop
    extra_hosts:
      - "host.docker.internal:host-gateway"

# Note: For best DLNA compatibility on macOS, consider running natively:
# cargo build --release && ./target/release/vuio --media-dir ./test-media