version: '3.8'

services:
  vuio:
    image: ghcr.io/vuiodev/vuio:latest
    container_name: vuio-server
    restart: unless-stopped
    
    # Use host networking for DLNA/UPnP compatibility
    network_mode: host
    
    volumes:
      # Persist configuration and database
      - ./vuio-config:/config
      # Mount your media library (adjust path as needed)
      - /path/to/your/media:/media
      
    environment:
      # User/Group ID mapping
      - PUID=1000  # Run 'id -u' to find your user ID
      - PGID=1000  # Run 'id -g' to find your group ID
      
      # Application configuration
      - VUIO_PORT=8080
      - VUIO_MEDIA_DIR=/media
      - VUIO_SERVER_NAME=VuIO
      - VUIO_BIND_INTERFACE=0.0.0.0
      
      # Let Vuio auto-detect the best interface
      - VUIO_SSDP_INTERFACE=Auto
      
      # Set server IP for DLNA announcements (Docker/container environments)
      # Uncomment and set to your host machine's IP address for proper DLNA discovery
      # - VUIO_SERVER_IP=192.168.1.100