//! Turns the committed `dist/` tree into a table the library can serve from.
//!
//! `web/ui.rs` in `vuio-core` lists its assets by hand, which works because a
//! human named those files. SvelteKit does not: every bundle carries a content
//! hash (`entry/app.Bx2SGeON.js`), so the names change on most builds and can
//! only be discovered by looking. Hence a generated table rather than a
//! hand-written `match`.

use std::{
    fs,
    path::{Path, PathBuf},
};

fn main() {
    let crate_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let dist = crate_dir.join("dist");

    // Rerunning on the directory catches additions and deletions, which a list
    // of individual files would not.
    println!("cargo:rerun-if-changed={}", dist.display());
    println!("cargo:rerun-if-changed=build.rs");

    let mut files = Vec::new();
    collect(&dist, &dist, &mut files);
    files.sort();

    if !files.iter().any(|(route, _)| route == "/index.html") {
        panic!(
            "no {} — run scripts/build-web.sh to build the web UI before compiling",
            dist.join("index.html").display()
        );
    }

    // Crate-private: which files the build produced is an implementation
    // detail, and `routes()` is the whole public surface.
    let mut generated = String::from(
        "// @generated by build.rs from dist/. Do not edit.\n\
         /// Every file of the built app, as (URL path, content type, bytes),\n\
         /// sorted by path.\n\
         static ASSETS: &[(&str, &str, &[u8])] = &[\n",
    );
    for (route, path) in &files {
        generated.push_str(&format!(
            "    ({:?}, {:?}, include_bytes!({:?})),\n",
            route,
            content_type(route),
            path.to_str().expect("dist paths are UTF-8"),
        ));
    }
    generated.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("assets.rs");
    fs::write(&out, generated).expect("failed to write the asset table");
}

/// Every file under `dist`, as (URL path, absolute source path).
fn collect(root: &Path, directory: &Path, files: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = fs::read_dir(directory) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, files);
            continue;
        }
        let Ok(relative) = path.strip_prefix(root) else {
            continue;
        };
        // Built on Windows too, where `components` yields backslashes that would
        // never match a request path.
        let route = relative
            .components()
            .map(|component| component.as_os_str().to_string_lossy().into_owned())
            .collect::<Vec<_>>()
            .join("/");
        files.push((format!("/{route}"), path));
    }
}

/// The only types SvelteKit and this app's `static/` actually emit, plus the
/// handful a future asset is likely to be. Anything unrecognised is served as
/// an opaque download rather than guessed at, because a wrong `Content-Type`
/// on a script is a silent failure in the browser.
fn content_type(route: &str) -> &'static str {
    match route.rsplit('.').next().unwrap_or_default() {
        "html" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json; charset=utf-8",
        "svg" => "image/svg+xml; charset=utf-8",
        "txt" => "text/plain; charset=utf-8",
        "mp4" => "video/mp4",
        "webm" => "video/webm",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "avif" => "image/avif",
        "ico" => "image/x-icon",
        "woff2" => "font/woff2",
        "woff" => "font/woff",
        "ttf" => "font/ttf",
        _ => "application/octet-stream",
    }
}
