name: Release

# This workflow runs on pushes to main/develop branches and on pull requests
on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*' # Also run on version tags (e.g., v1.0.0)
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  # The name of your binary. This is used for packaging.
  BINARY_NAME: vuio 

jobs:
  # ===================================================================
  # Job 1: Run Tests and Checks on all Platforms (for PRs and pushes)
  # ===================================================================
  test_and_check:
    name: Test on ${{ matrix.os-arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # x86_64 builds
          - os: ubuntu-latest
            os-arch: Linux-x86_64
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            os-arch: Windows-x86_64
            target: x86_64-pc-windows-gnu
          - os: macos-13 # x86 runner
            os-arch: macOS-x86_64
            target: x86_64-apple-darwin
          # aarch64 (ARM) builds
          - os: ubuntu-latest
            os-arch: Linux-aarch64
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            os-arch: Windows-aarch64
            target: aarch64-pc-windows-gnu
          - os: macos-14 # ARM runner (M1/M2)
            os-arch: macOS-aarch64
            target: aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Cache Cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          # Install linker for ARM cross-compile on x86 runner
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            sudo apt-get install -y gcc-aarch64-linux-gnu
          fi
          sudo apt-get install -y libssl-dev pkg-config

      - name: Build project
        run: cargo build --target ${{ matrix.target }}
        env:
          # Set linker for ARM cross-compilation on Linux
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

  # ===================================================================
  # Job 2: Build Release Artifacts (runs ONLY on new version tags)
  # ===================================================================
  build_release_artifacts:
    name: Build release for ${{ matrix.os-arch }}
    # This job only runs when a tag is pushed
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}
    needs: test_and_check # Ensure tests pass before building release
    strategy:
      fail-fast: false
      matrix:
        include:
          # x86_64 targets
          - os: ubuntu-latest
            os-arch: linux-x86_64
            target: x86_64-unknown-linux-gnu
            asset_ext: .tar.gz
          - os: windows-latest
            os-arch: windows-x86_64
            target: x86_64-pc-windows-gnu
            asset_ext: .exe
          - os: macos-13 # x86 runner
            os-arch: macos-x86_64
            target: x86_64-apple-darwin
            asset_ext: .tar.gz
          # aarch64 (ARM) targets
          - os: ubuntu-latest
            os-arch: linux-arm64
            target: aarch64-unknown-linux-gnu
            asset_ext: .tar.gz
          - os: windows-latest
            os-arch: windows-arm64
            target: aarch64-pc-windows-gnu
            asset_ext: .exe
          - os: macos-14 # ARM runner (M1/M2)
            os-arch: macos-arm64
            target: aarch64-apple-darwin
            asset_ext: .tar.gz

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      # Install NSIS for Windows installer
      - name: Install NSIS
        if: runner.os == 'Windows'
        run: choco install nsis

      # Install linker for Linux ARM cross-build
      - name: Install build dependencies (Linux)
        if: runner.os == 'Linux' && matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}
        env:
          # Set linker for ARM cross-compilation on Linux
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc

      - name: Package artifacts
        shell: bash
        run: |
          # Define source and output paths/names
          VERSION=${GITHUB_REF_NAME#v}
          BINARY_PATH_PREFIX="target/${{ matrix.target }}/release"
          ASSET_NAME="${{ env.BINARY_NAME }}-${{ matrix.os-arch }}${{ matrix.asset_ext }}"

          if [ "${{ runner.os }}" == "Windows" ]; then
            # Windows: Create NSIS installer
            # Note: NSIS needs to be on the PATH, choco does this
            BINARY_FILE="${{ env.BINARY_NAME }}.exe"
            cp "$BINARY_PATH_PREFIX/$BINARY_FILE" .
            makensis -V2 -DVERSION=$VERSION -DAPP_EXE=$BINARY_FILE -DOUTFILE=$ASSET_NAME installer.nsi
          else
            # Linux/macOS: Create a compressed tarball
            tar -czf "$ASSET_NAME" -C "$BINARY_PATH_PREFIX" "${{ env.BINARY_NAME }}"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: ${{ env.BINARY_NAME }}-*

  # ===================================================================
  # Job 3: Create GitHub Release (runs ONLY on new version tags)
  # ===================================================================
  create_github_release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build_release_artifacts # This job runs after all matrix builds are complete
    permissions:
      contents: write # Required to create a release

    steps:
      - name: Download all release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: release-artifacts

      - name: Create GitHub Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          # This will create a draft release. Remove `draft: true` to publish automatically.
          draft: true
          files: release-artifacts/*